### ISSUE TITLE
[BUG] '총 좌식 생활 시간'이 변하지 않음

### ISSUE THREAD

**Issue by YugyeongJung** [woohyeok-choi/Stochastic-StandUp#11]
**버전 정보**
- 스마트폰 모델명: 갤럭시 노트 10S
- 안드로이드 OS 버전: 10
- 앱 버전: 0.0.6

**버그 요약**
어떠한 버그인지 한 줄 이내로 요약
'총 좌식 생활 시간'이 0에서 변하지 않음

**버그 발생 상황**
해당 버그를 발생 시키기 위한 방법 설명

**원래 예상되는 동작**
버그가 나지 않았다면 어떻게 동작할 것이라고 예상되는 지 설명.

**스크린 샷**
가능하다면 버그가 발생한 스크린 샷 첨부.
![image](https://user-images.githubusercontent.com/63027011/79536700-a5f8b100-80bb-11ea-9a9e-df9815d554a4.png)

**기타**

**Comment by woohyeok-choi** [comment]
This bug may be fixed in 0.0.7; Please check it and close this issue if this bug does not occurs again.
