### ISSUE TITLE
[FEATURE] 대시보드 화면 UI 논의사항

### ISSUE THREAD

**Issue by YugyeongJung** [woohyeok-choi/Stochastic-StandUp#13]
**버전 정보**
- 스마트폰 모델명:
- 안드로이드 OS 버전:
- 앱 버전:

**현재 서비스가 제공하는 기능의 부족한 점**
기존 대시보드 상단의 원 그래프의 표시 방식이 명확하지 않음
1. 원을 다 채웠을 때의 시간 기준이 각 원마나 달라서 총 좌식 생활 시간=평균 좌식 시간 이어도 실제로 그래프에는 다른 크기로 표시됨
2. 총 좌식 생활 시간은 누적되지만 평균 좌식 생활 시간은 누적이 아니기 때문에 두 그래프를 비교하는 것에 의미가 없음.
3. 총 좌식 생활 시간, 평균 좌식 생활 시간, 오래 앉아있는 횟수 중 평균 좌식 생활 시간을 제외하곤 유저가 직관적으로 이해하기 어려움 

**추가 또는 수정 방향**
1. 상단 원 그래프에는 받은 포인트와 미션 성공 횟수를 표시
2. 중간 부분에는 받은 포인트 수치와 미션 성공 횟수를 숫자로 표시
3. 하단 부분에는 받은 포인트(line graph)와 평균 좌식 시간(bar graph)을 표시하고, 이를 주간 차트로 표기

**기타**

**Comment by woohyeok-choi** [comment]
1. For circles on the top and panels on the middle, the number of successful missions and incentive obtained are shown.
2. For a weekly chart, average sedentary minutes and incentive obtained are presented.
