### ISSUE TITLE
[BUG] 착석 상태 인식 오류

### ISSUE THREAD

**Issue by juhojuho** [woohyeok-choi/Stochastic-StandUp#14]
**버전 정보**
- 스마트폰 모델명: LG G7
- 안드로이드 OS 버전: 9.0
- 앱 버전:  0.08

**버그 요약**
착석 상태가 제대로 인식되지 않음

**버그 발생 상황**
자리에 앉아있어도 걷고 있는 중이라 인식됨

**원래 예상되는 동작**
자리에 앉아있을 시 착석 상태로 인식되어야 함

**스크린 샷**

**기타**
참고로 BeActive는 걷고 있어도 착석 상태로 인식되더라구요. 비액티브도 원래 잘 작동했는데 최근에 좀 이상해진 거 같아요.

**Comment by woohyeok-choi** [comment]
이거 노티 바에서 그렇게 나오는 겁니까? 아니면 다른 데서?

**Comment by woohyeok-choi** [comment]
스텝 카운트 기반으로 바꿔서 인식 잘 되게 수정함.
