### ISSUE TITLE
[BUG] 미션 오류

### ISSUE THREAD

**Issue by juhojuho** [woohyeok-choi/Stochastic-StandUp#15]
**버전 정보**
- 스마트폰 모델명: G7
- 안드로이드 OS 버전: 9.0
- 앱 버전: 0.1.1

**버그 요약**
기립 미션이 떠서 일어나서 3분 정도 걸었는데 성공 인식 안 됨

**버그 발생 상황**
기립 미션 후 자리에서 일어나 걸음

**원래 예상되는 동작**
3분 정도 걸으면 미션 성공이 되야할 것 같음

**기타**
3시 5분쯤 미션이 떠서 3시10분~13분까지 걸음

**Comment by woohyeok-choi** [comment]
스텝 카운트 기반으로 바꿔서 인식 잘 되게 수정함.
