### ISSUE TITLE
[BUG] 방해금지 모드에서 음수 발생

### ISSUE THREAD

**Issue by cheonsol-lee** [woohyeok-choi/Stochastic-StandUp#16]
**버전 정보**
- 스마트폰 모델명: Galaxy S9+
- 안드로이드 OS 버전: Android 10
- 앱 버전: 0.1.14

**버그 요약**
방해금지 모드를 계속 누르면 음수까지 가능합니다.

**버그 발생 상황**
"방해금지모드 → 시간입력 → 확인"을 반복하면 음수까지 도달가능

**원래 예상되는 동작**
0회 설정 가능 후 방해금지모드를 더 실행시킬시 
Toast로 "방해금지 모드를 모두 사용하셨습니다." 또는 더이상 허가 안되도록 막아야 합니다.

**스크린 샷**
![image](https://user-images.githubusercontent.com/28869864/80069885-0f296a00-857d-11ea-943c-1a352e8d3a25.png)

**Comment by woohyeok-choi** [comment]
역시 값 업데이트가 제대로 되지 않아 발생. 수정 완료.
