### ISSUE TITLE
[FEATURE] 미션수행 및 활동추적시간이 10시간 이후부터 가능

### ISSUE THREAD

**Issue by cheonsol-lee** [woohyeok-choi/Stochastic-StandUp#17]
**버전 정보**
- 스마트폰 모델명: Galaxy S9+
- 안드로이드 OS 버전: Android10
- 앱 버전: 0.1.4

**현재 서비스가 제공하는 기능의 부족한 점**
미션 수행 및 활동추적시간이 최소 12시간 이상이라 기재되어 있으나
10시간 이후부터 가능함

**추가 또는 수정 방향**
2가지 방법 가능
1. 문구를 10시간 이상으로 수정 
2. 12시간 이상만 가능하게 끔 수정

**기타**
![image](https://user-images.githubusercontent.com/28869864/80070558-1604ac80-857e-11ea-8daa-c44637115097.png)

**Comment by woohyeok-choi** [comment]
값 업데이트가 제대로 되지 않아 발생함. 수정 완료.
